// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcex8SCygsrnOw4FDYuW5sKqfvxy0_Rn8',
    appId: '1:183946139050:web:20cc3f7cdd67dbb5cf47d3',
    messagingSenderId: '183946139050',
    projectId: 'store-app-5ae02',
    authDomain: 'store-app-5ae02.firebaseapp.com',
    storageBucket: 'store-app-5ae02.appspot.com',
    measurementId: 'G-KR1X3M13JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-lpuRxeB-KM1Xq_ocGWkLtayztDIv8h4',
    appId: '1:183946139050:android:e034eb765f02595ccf47d3',
    messagingSenderId: '183946139050',
    projectId: 'store-app-5ae02',
    storageBucket: 'store-app-5ae02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-5A7pWr1aQE2mDuVaELgGMe-S_40V3L8',
    appId: '1:183946139050:ios:1ecd824ede8107ffcf47d3',
    messagingSenderId: '183946139050',
    projectId: 'store-app-5ae02',
    storageBucket: 'store-app-5ae02.appspot.com',
    iosBundleId: 'com.example.stroreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-5A7pWr1aQE2mDuVaELgGMe-S_40V3L8',
    appId: '1:183946139050:ios:1ecd824ede8107ffcf47d3',
    messagingSenderId: '183946139050',
    projectId: 'store-app-5ae02',
    storageBucket: 'store-app-5ae02.appspot.com',
    iosBundleId: 'com.example.stroreApp',
  );
}
